apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie-ing
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: mealie.malazan.wu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mealie-svc
            port:
              number: 80
